using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace dotMorten.Unifi.Protect.DataModels
{
    // TODO: Most of these classes are autogenerated, and needs some clean up and merging - properties of type object needs proper models

    public class Motion
    {
        public int Today { get; set; }
        public int Average { get; set; }
        public List<int> LastDays { get; set; }
        public List<int> RecentHours { get; set; }
    }

    public class Smart
    {
        public int Today { get; set; }
        public int Average { get; set; }
        public List<int> LastDays { get; set; }
    }

    public class EventStats
    {
        public Motion Motion { get; set; }
        public Smart Smart { get; set; }
    }

    public class WiredConnectionState
    {
        public int? PhyRate { get; set; }
    }

    public class Channel
    {
        public int id { get; set; }
        public string videoId { get; set; }
        public string name { get; set; }
        public bool enabled { get; set; }
        public bool isRtspEnabled { get; set; }
        public string rtspAlias { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public int fps { get; set; }
        public int bitrate { get; set; }
        public int minBitrate { get; set; }
        public int maxBitrate { get; set; }
        public int minClientAdaptiveBitRate { get; set; }
        public int minMotionAdaptiveBitRate { get; set; }
        public List<int> fpsValues { get; set; }
        public int idrInterval { get; set; }
    }

    public class IspSettings
    {
        public string aeMode { get; set; }
        public string irLedMode { get; set; }
        public int irLedLevel { get; set; }
        public int wdr { get; set; }
        public int icrSensitivity { get; set; }
        public int brightness { get; set; }
        public int contrast { get; set; }
        public int hue { get; set; }
        public int saturation { get; set; }
        public int sharpness { get; set; }
        public int denoise { get; set; }
        public bool isFlippedVertical { get; set; }
        public bool isFlippedHorizontal { get; set; }
        public bool isAutoRotateEnabled { get; set; }
        public bool isLdcEnabled { get; set; }
        public bool is3dnrEnabled { get; set; }
        public bool isExternalIrEnabled { get; set; }
        public bool isAggressiveAntiFlickerEnabled { get; set; }
        public bool isPauseMotionEnabled { get; set; }
        public int dZoomCenterX { get; set; }
        public int dZoomCenterY { get; set; }
        public int dZoomScale { get; set; }
        public int dZoomStreamId { get; set; }
        public string focusMode { get; set; }
        public int focusPosition { get; set; }
        public int? touchFocusX { get; set; }
        public int? touchFocusY { get; set; }
        public int zoomPosition { get; set; }
    }

    public class TalkbackSettings
    {
        public string typeFmt { get; set; }
        public string typeIn { get; set; }
        public string bindAddr { get; set; }
        public int bindPort { get; set; }
        public object filterAddr { get; set; }
        public object filterPort { get; set; }
        public int channels { get; set; }
        public int samplingRate { get; set; }
        public int bitsPerSample { get; set; }
        public int quality { get; set; }
    }

    public class OsdSettings
    {
        public bool IsNameEnabled { get; set; }
        public bool IsDateEnabled { get; set; }
        public bool IsLogoEnabled { get; set; }
        public bool IsDebugEnabled { get; set; }
    }

    public class LedSettings
    {
        public bool IsEnabled { get; set; }
        public int BlinkRate { get; set; }
    }

    public class SpeakerSettings
    {
        public bool IsEnabled { get; set; }
        public bool AreSystemSoundsEnabled { get; set; }
        public int Volume { get; set; }
    }

    public class RecordingSettings
    {
        public int PrePaddingSecs { get; set; }
        public int PostPaddingSecs { get; set; }
        public int MinMotionEventTrigger { get; set; }
        public int EndMotionEventDelay { get; set; }
        public bool SuppressIlluminationSurge { get; set; }
        public string Mode { get; set; }
        public string Geofencing { get; set; }
        public string MotionAlgorithm { get; set; }
        public bool EnablePirTimelapse { get; set; }
        public bool UseNewMotionAlgorithm { get; set; }
        public object RetentionDurationMs { get; set; }
    }

    public class SmartDetectSettings
    {
        public List<string> ObjectTypes { get; set; }
    }

    public class MotionZone
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public List<List<double>> Points { get; set; }
        public int Sensitivity { get; set; }
    }

    public class SmartDetectZone
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public List<List<double>> Points { get; set; }
        public int Sensitivity { get; set; }
        public List<string> ObjectTypes { get; set; }
    }

    public class Wifi
    {
        public int? Channel { get; set; }
        public int? Frequency { get; set; }
        public int? LinkSpeedMbps { get; set; }
        public int SignalQuality { get; set; }
        public int SignalStrength { get; set; }
    }

    public class Battery
    {
        public object Percentage { get; set; }
        public bool IsCharging { get; set; }
        public string SleepState { get; set; }
    }

    public class Video
    {
        public object RecordingStart { get; set; }
        public object RecordingEnd { get; set; }
        public object RecordingStartLQ { get; set; }
        public object RecordingEndLQ { get; set; }
        public object TimelapseStart { get; set; }
        public object TimelapseEnd { get; set; }
        public object TimelapseStartLQ { get; set; }
        public object TimelapseEndLQ { get; set; }
    }

    public class Storage
    {
        public object Used { get; set; }
        public double Rate { get; set; }
        public long Available { get; set; }
        public bool IsRecycling { get; set; }
        public long Size { get; set; }
        public string Type { get; set; }
        public List<Device> Devices { get; set; }
    }

    public class Stats
    {
        public object RxBytes { get; set; }
        public object TxBytes { get; set; }
        public Wifi WiFi { get; set; }
        public Battery Battery { get; set; }
        public Video Video { get; set; }
        public Storage Storage { get; set; }
        public int WiFiQuality { get; set; }
        public int WiFiStrength { get; set; }
    }

    public class PrivacyMaskCapability
    {
        public int MaxMasks { get; set; }
        public bool RectangleOnly { get; set; }
    }

    public class Steps
    {
        public object Max { get; set; }
        public object Min { get; set; }
        public object Step { get; set; }
    }

    public class Degrees
    {
        public object Max { get; set; }
        public object Min { get; set; }
        public object Step { get; set; }
    }

    public class Focus
    {
        public Steps Steps { get; set; }
        public Degrees Degrees { get; set; }
    }

    public class Pan
    {
        public Steps Steps { get; set; }
        public Degrees Degrees { get; set; }
    }

    public class Tilt
    {
        public Steps Steps { get; set; }
        public Degrees Degrees { get; set; }
    }

    public class Zoom
    {
        public Steps Steps { get; set; }
        public Degrees Degrees { get; set; }
    }

    public class FeatureFlags
    {
        public bool canAdjustIrLedLevel { get; set; }
        public bool canMagicZoom { get; set; }
        public bool canOpticalZoom { get; set; }
        public bool canTouchFocus { get; set; }
        public bool hasAccelerometer { get; set; }
        public bool hasAec { get; set; }
        public bool hasBattery { get; set; }
        public bool hasBluetooth { get; set; }
        public bool hasChime { get; set; }
        public bool hasExternalIr { get; set; }
        public bool hasIcrSensitivity { get; set; }
        public bool hasLdc { get; set; }
        public bool hasLedIr { get; set; }
        public bool hasLedStatus { get; set; }
        public bool hasLineIn { get; set; }
        public bool hasMic { get; set; }
        public bool hasPrivacyMask { get; set; }
        public bool hasRtc { get; set; }
        public bool hasSdCard { get; set; }
        public bool hasSpeaker { get; set; }
        public bool hasWifi { get; set; }
        public bool hasHdr { get; set; }
        public bool hasAutoICROnly { get; set; }
        public List<string> videoModes { get; set; }
        public List<int> videoModeMaxFps { get; set; }
        public bool hasMotionZones { get; set; }
        public bool hasLcdScreen { get; set; }
        public List<string> smartDetectTypes { get; set; }
        public List<string> motionAlgorithms { get; set; }
        public PrivacyMaskCapability privacyMaskCapability { get; set; }
        public Focus focus { get; set; }
        public Pan pan { get; set; }
        public Tilt tilt { get; set; }
        public Zoom zoom { get; set; }
        public bool hasSmartDetect { get; set; }
        public bool beta { get; set; }
        public bool dev { get; set; }
    }

    public class PirSettings
    {
        public int PirSensitivity { get; set; }
        public int PirMotionClipLength { get; set; }
        public int TimelapseFrameInterval { get; set; }
        public int TimelapseTransferInterval { get; set; }
    }

    public class LcdMessage
    {
        public string Type { get; set; }
        public string Text { get; set; }
        public object ResetAt { get; set; }
    }

    public class WifiConnectionState
    {
        public object Channel { get; set; }
        public object Frequency { get; set; }
        public object PhyRate { get; set; }
        public object SignalQuality { get; set; }
        public object SignalStrength { get; set; }
    }

    public class Camera : ProtectNetworkDevice
    {
        public bool IsDeleting { get; set; }
        public string ConnectionHost { get; set; }
        public string Type { get; set; }
        public object UpSince { get; set; }
        public object LastSeen { get; set; }
        public object ConnectedSince { get; set; }
        public string State { get; set; }
        public string HardwareRevision { get; set; }
        public string FirmwareVersion { get; set; }
        public string LatestFirmwareVersion { get; set; }
        public string FirmwareBuild { get; set; }
        public bool IsUpdating { get; set; }
        public bool IsAdopting { get; set; }
        public bool IsAdopted { get; set; }
        public bool IsAdoptedByOther { get; set; }
        public bool IsProvisioned { get; set; }
        public bool IsRebooting { get; set; }
        public bool? IsSshEnabled { get; set; }
        public bool CanAdopt { get; set; }
        public bool IsAttemptingToConnect { get; set; }
        public object LastMotion { get; set; }
        public int MicVolume { get; set; }
        public bool IsMicEnabled { get; set; }
        public bool IsRecording { get; set; }
        public bool IsMotionDetected { get; set; }
        public int PhyRate { get; set; }
        public bool? HdrMode { get; set; }
        public string VideoMode { get; set; }
        public bool IsProbingForWifi { get; set; }
        public object APMac { get; set; }
        public object APRssi { get; set; }
        public object ElementInfo { get; set; }
        public int ChimeDuration { get; set; }
        public bool IsDark { get; set; }
        public object LastPrivacyZonePositionId { get; set; }
        public long? LastRing { get; set; }
        public bool IsLiveHeatmapEnabled { get; set; }
        public string AnonymousDeviceId { get; set; }
        public EventStats EventStats { get; set; }
        public WiredConnectionState WiredConnectionState { get; set; }
        public List<Channel> Channels { get; set; }
        public IspSettings IspSettings { get; set; }
        public TalkbackSettings TalkbackSettings { get; set; }
        public OsdSettings OsdSettings { get; set; }
        public LedSettings LedSettings { get; set; }
        public SpeakerSettings SpeakerSettings { get; set; }
        public RecordingSettings RecordingSettings { get; set; }
        public SmartDetectSettings SmartDetectSettings { get; set; }
        public object RecordingSchedule { get; set; }
        public List<MotionZone> MotionZones { get; set; }
        public List<object> PrivacyZones { get; set; }
        public List<SmartDetectZone> SmartDetectZones { get; set; }
        public List<object> SmartDetectLines { get; set; }
        public Stats Stats { get; set; }
        public FeatureFlags FeatureFlags { get; set; }
        public PirSettings PirSettings { get; set; }
        public LcdMessage LcdMessage { get; set; }
        public WifiConnectionState WiFiConnectionState { get; set; }
        public bool IsConnected { get; set; }
        public string Platform { get; set; }
        public bool HasSpeaker { get; set; }
        public bool HasWifi { get; set; }
        public int AudioBitrate { get; set; }
        public bool CanManage { get; set; }
        public bool IsManaged { get; set; }
        public List<object> ConnectDisconnect { get; set; }
        public List<string> Motion { get; set; }
        public string camera { get; set; }
        public List<string> Ring { get; set; }
        public override string ToString() => $"{Name} - {Type} ({Id})";
    }

    public class Flags
    {
    }

    public class Web
    {
        [JsonProperty("liveview.includeGlobal")]
        public bool LiveViewIncludeGlobal { get; set; }
    }

    public class Settings
    {
        public Flags Flags { get; set; }
        public Web Web { get; set; }
        public List<string> CameraOrder { get; set; }
    }

    public class Location
    {
        public bool IsAway { get; set; }
        public long HomeAwaySince { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public string ModelKey { get; set; }
    }

    public class Schedule
    {
        public List<object> Items { get; set; }
    }

    public class System
    {
        public List<object> ConnectDisconnect { get; set; }
        public List<object> Update { get; set; }
    }

    public class User : ProtectDevice
    {
        public List<object> arrive { get; set; }
        public List<object> depart { get; set; }
        public string user { get; set; }
        public List<string> permissions { get; set; }
        public string lastLoginIp { get; set; }
        public long? lastLoginTime { get; set; }
        public bool isOwner { get; set; }
        public bool enableNotifications { get; set; }
        public Settings settings { get; set; }
        public List<string> groups { get; set; }
        public Location location { get; set; }
        public List<AlertRule> alertRules { get; set; }
        public bool hasAcceptedInvite { get; set; }
        public List<string> allPermissions { get; set; }
        public CloudAccount cloudAccount { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string localUsername { get; set; }
    }

    public class AlertRule
    {
        public string Id { get; set; }
        public string Mame { get; set; }
        public string When { get; set; }
        public Schedule Schedule { get; set; }
        public System System { get; set; }
        public List<Camera> Cameras { get; set; }
        public List<User> Users { get; set; }
        public string Geofencing { get; set; }
    }

    public class CloudAccount : ProtectDevice
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public object ProfileImg { get; set; }
        public string User { get; set; }
        public string CloudId { get; set; }
        public Location Location { get; set; }
    }

    public class Group : ProtectDevice
    {
        public List<string> Permissions { get; set; }
        public string Type { get; set; }
        public bool IsDefault { get; set; }
    }

    public class Slot
    {
        public List<string> Cameras { get; set; }
        public string CycleMode { get; set; }
        public int CycleInterval { get; set; }
    }

    public class LiveView : ProtectDevice
    {
        public bool IsDefault { get; set; }
        public bool IsGlobal { get; set; }
        public int Layout { get; set; }
        public List<Slot> Slots { get; set; }
        public string Owner { get; set; }
    }

    public class Ports
    {
        public int ump { get; set; }
        public int http { get; set; }
        public int https { get; set; }
        public int rtsp { get; set; }
        public int rtsps { get; set; }
        public int rtmp { get; set; }
        public int devicesWss { get; set; }
        public int cameraHttps { get; set; }
        public int cameraTcp { get; set; }
        public int liveWs { get; set; }
        public int liveWss { get; set; }
        public int tcpStreams { get; set; }
        public int playback { get; set; }
        public int emsCLI { get; set; }
        public int emsLiveFLV { get; set; }
        public int cameraEvents { get; set; }
        public int tcpBridge { get; set; }
        public int ucore { get; set; }
        public int discoveryClient { get; set; }
    }

    public class WifiSettings
    {
        public bool useThirdPartyWifi { get; set; }
        public object ssid { get; set; }
        public object password { get; set; }
    }

    public class LocationSettings
    {
        public bool isAway { get; set; }
        public bool isGeofencingEnabled { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public int radius { get; set; }
    }

    public class Cpu
    {
        public double averageLoad { get; set; }
        public double temperature { get; set; }
    }

    public class Memory
    {
        public int available { get; set; }
        public int free { get; set; }
        public int total { get; set; }
    }

    public class Device
    {
        public string model { get; set; }
        public long size { get; set; }
        public bool healthy { get; set; }
    }

    public class Tmpfs
    {
        public int available { get; set; }
        public int total { get; set; }
        public int used { get; set; }
        public string path { get; set; }
    }

    public class SystemInfo
    {
        public Cpu cpu { get; set; }
        public Memory memory { get; set; }
        public Storage storage { get; set; }
        public Tmpfs tmpfs { get; set; }
    }

    public class AllMessage
    {
        public string type { get; set; }
        public string text { get; set; }
    }

    public class DoorbellSettings
    {
        public string defaultMessageText { get; set; }
        public int defaultMessageResetTimeoutMs { get; set; }
        public List<object> customMessages { get; set; }
        public List<AllMessage> allMessages { get; set; }
    }

    public class SmartDetectAgreement
    {
        public string status { get; set; }
        public long lastUpdateAt { get; set; }
    }

    public class RecordingSpace
    {
        public long total { get; set; }
        public long used { get; set; }
        public long available { get; set; }
    }

    public class StorageStats
    {
        public double utilization { get; set; }
        public long capacity { get; set; }
        public int remainingCapacity { get; set; }
        public RecordingSpace recordingSpace { get; set; }
    }

    public class MaxCameraCapacity
    {
        public int _4K { get; set; }
        public int HD { get; set; }
    }

    public class Nvr : ProtectNetworkDevice
    {
        public bool canAutoUpdate { get; set; }
        public bool isStatsGatheringEnabled { get; set; }
        public string timezone { get; set; }
        public string version { get; set; }
        public string firmwareVersion { get; set; }
        public object uiVersion { get; set; }
        public string hardwarePlatform { get; set; }
        public Ports ports { get; set; }
        public int uptime { get; set; }
        public long lastSeen { get; set; }
        public bool isUpdating { get; set; }
        public long lastUpdateAt { get; set; }
        public bool isStation { get; set; }
        public bool enableAutomaticBackups { get; set; }
        public bool enableStatsReporting { get; set; }
        public bool isSshEnabled { get; set; }
        public object errorCode { get; set; }
        public string releaseChannel { get; set; }
        public List<string> hosts { get; set; }
        public bool enableBridgeAutoAdoption { get; set; }
        public string hardwareId { get; set; }
        public string hardwareRevision { get; set; }
        public int hostType { get; set; }
        public string hostShortname { get; set; }
        public bool isHardware { get; set; }
        public string timeFormat { get; set; }
        public object recordingRetentionDurationMs { get; set; }
        public bool enableCrashReporting { get; set; }
        public object disableAudio { get; set; }
        public string analyticsData { get; set; }
        public string anonymousDeviceId { get; set; }
        public int cameraUtilization { get; set; }
        public bool isRecycling { get; set; }
        public WifiSettings wifiSettings { get; set; }
        public LocationSettings locationSettings { get; set; }
        public FeatureFlags featureFlags { get; set; }
        public SystemInfo systemInfo { get; set; }
        public DoorbellSettings doorbellSettings { get; set; }
        public SmartDetectAgreement smartDetectAgreement { get; set; }
        public StorageStats storageStats { get; set; }
        public bool isAway { get; set; }
        public bool isSetup { get; set; }
        public string network { get; set; }
        public string type { get; set; }
        public long upSince { get; set; }
        public bool isRecordingDisabled { get; set; }
        public MaxCameraCapacity maxCameraCapacity { get; set; }
        public override string ToString() => $"{Name} ({Id})";
    }

    public class Bridge : ProtectNetworkDevice
    {
        public string ConnectionHost { get; set; }
        public string Type { get; set; }
        public long UpSince { get; set; }
        public long LastSeen { get; set; }
        public long ConnectedSince { get; set; }
        public string State { get; set; }
        public int HardwareRevision { get; set; }
        public string FirmwareVersion { get; set; }
        public object LatestFirmwareVersion { get; set; }
        public object FirmwareBuild { get; set; }
        public bool IsUpdating { get; set; }
        public bool IsAdopting { get; set; }
        public bool IsAdopted { get; set; }
        public bool IsAdoptedByOther { get; set; }
        public bool IsProvisioned { get; set; }
        public bool IsRebooting { get; set; }
        public bool IsSshEnabled { get; set; }
        public bool CanAdopt { get; set; }
        public bool IsAttemptingToConnect { get; set; }
        public WiredConnectionState WiredConnectionState { get; set; }
        public bool IsConnected { get; set; }
        public string Platform { get; set; }
        public override string ToString() => $"{Name} ({Id})";
    }
    public abstract class ProtectDevice
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ModelKey { get; set; }
    }
    public abstract class ProtectNetworkDevice : ProtectDevice
    {
        public string Mac { get; set; }
        public string Host { get; set; }
    }

    public class ProtectSystemStatus
    {
        public string AuthUserId { get; set; }
        public string AccessKey { get; set; }
        public List<Camera> Cameras { get; set; }
        public List<User> Users { get; set; }
        public List<Group> Groups { get; set; }
        public List<LiveView> LiveViews { get; set; }
        public Nvr Nvr { get; set; }
        public List<object> LegacyUFVs { get; set; }
        public string LastUpdateId { get; set; }
        public List<object> Viewers { get; set; }
        public List<object> Displays { get; set; }
        public List<object> Lights { get; set; }
        public List<Bridge> Bridges { get; set; }
        public List<object> Sensors { get; set; }
        public List<object> Doorlocks { get; set; }
    }


}
